name: CI

on: [push]

jobs:
  test-ayoayo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ayoayo
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: npm install and build
        run: |
          npm ci
          npm run test

  gh-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ayoayo-web

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: npm install and build
        run: |
          npm ci
          npm run build
      - uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: ayoayo-web/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
